# -*- coding: utf-8 -*-
from pathlib import Path

path = Path("src/pipeline/llm.py")
text = path.read_text(encoding="utf-8")
old = "        opening_lines = [\n            f\"{team_a} surge down the flank, quick passes slicing through the press and the stands erupting with each touch!\",\n            f\"A lightning break from {team_b}, the through ball splits the line and the cutback is begging to be finished!\"\n        ]\n        closing_options = [\n            \"It is a thunderous finish that rockets toward the top corner!\",\n            \"The shot arrows low toward the far post and the keeper is stranded!\",\n            \"A delicate dink loops over the keeper and settles sweetly!\",\n            \"The volley thumps off the turf and into the roof of the net!\"\n        ]\n        commentary = f\"{random.choice(opening_lines)} {random.choice(closing_options)}\"\n\n        if language.startswith(\"es\"):\n            commentary = (\n                f\"{team_a} acelera con valentia, toques rapidos que rompen lineas y animan a la grada. \"\n                f\"Remate {random.choice(['potente', 'imparable', 'colocado'])} que busca la escuadra para desatar la locura!\"\n            )\n        elif language.startswith(\"ko\"):\n            commentary = (\n                f\"{team_a} sprints down the touchline, crisp passing slices open the defence and fans roar louder. \"\n                f\"The strike {random.choice(['drives toward the far corner', 'clips the bar on its way out', 'rattles the net with authority'])}!\"\n            )\n        return commentary\n"
new = "        opening_lines = [\n            f\"{team_a} are flying forward, one-touch football shredding the press and the crowd is on its feet!\",\n            f\"Listen to the roar! {team_b} rip through midfield, a give-and-go opens acres of grass and the box is chaos!\",\n            f\"You can feel the electricity! {team_a} sling a whipped cross in, bodies hurling at the near post!\"\n        ]\n        finishers = [\n            \"IT'S A STUNNER THAT RATTLES THE TOP BINS!!!\",\n            \"GOAL! SENSATIONAL STRIKE, THE NET IS STILL SHAKING!!!\",\n            \"THE PLACE ERUPTS AS THAT CURLER KISSES THE FAR STANCHION!!!\",\n            \"WHAT A ROCKET, THE KEEPER'S BEATEN ALL ENDS UP!!!\"\n        ]\n        colour_calls = [\n            \"The touch, the vision, the finish — that's box-office football!\",\n            \"This ground is bouncing, you simply cannot script drama like this!\",\n            \"Championship tempo, heavyweight execution, and the fans are losing their minds!\",\n        ]\n        commentary = f\"{random.choice(opening_lines)} {random.choice(finishers)} {random.choice(colour_calls)}\"\n\n        if language.startswith(\"es\"):\n            commentary = (\n                f\"{team_a} rompe lineas con pura vertigo, pared y desmarque que enloquecen a la grada! \"\n                f\"GOOOOOOL! {random.choice(['Latigazo inapelable', 'Disparo teledirigido', 'Toque de seda'])} que besa la escuadra y hace temblar el estadio!!!\"\n            )\n        elif language.startswith(\"ko\"):\n            commentary = (\n                f\"{team_a}의 번개 같은 전진입니다! 패스가 번쩍이며 수비를 찢어 놓고 관중의 함성이 폭발합니다! \"\n                f\"마지막 슛이 {random.choice(['골대 상단을 갈라버립니다', '골문 구석으로 빨려 들어갑니다', '스토퍼를 지나며 그물을 뒤흔듭니다'])}!!!\"\n            )\n        return commentary\n"
if old not in text:
    raise SystemExit("Target block not found in llm fallback")
path.write_text(text.replace(old, new), encoding="utf-8")
